// [ uuid(36A385C8-A258-4210-A61C-EB3890501903), object, dual ]

// NOTE: Every function name is is in UpperCase style, as it all must match, since if you
// use 'output' somewhere, it'll turn later 'Output' names into 'output' and confuse the
// heck out of other clients who get the switcheroo pulled on them when you add new names
// that don't match the standard.  Note that this only affects the idl file, not us.

//#define _MIDL_DECLARE_WIREM_HANDLE // Used for handles like HWND, etc. Not currently needed
midl_pragma warning(disable: 2111) // identifier length exceeds 31 characters
midl_pragma warning(disable: 2366) // cannot assign a default value : var

[
   uuid(36A385C0-A258-4210-A61C-EB3890501903),
   helpstring("BeipMU 4.00")
]
library BeipMU
{
   importlib("stdole32.tlb");
   #include "OM_Props.idl"

   interface Connection;
   interface Window_Main;
   interface TextWindowLine;

   [ uuid(4be9e159-9074-446c-9fa3-c08fc97c5502), oleautomation, dual, nonextensible ]
   interface Window_Properties : IDispatch
   {
      [propget] HRESULT Title([out, retval] BSTR *title);
      [propput] HRESULT Title([in] BSTR title);

      [propget] HRESULT HWND([out, retval] __int3264 *hwnd);
   }

   typedef enum tagMouseButton
   {
      Left=0,
      Right=1,
      Middle=2
   } MouseButton;

   [ uuid(7401476A-2852-487f-9B4A-22927B1EC320), oleautomation, dual, nonextensible ]
   interface Window_Events : IDispatch
   {
      HRESULT SetOnClose([in, defaultvalue(0)] IDispatch *OnClose, [in, defaultvalue(0)] VARIANT userdata);
      HRESULT SetOnMouseMove([in, defaultvalue(0)] IDispatch *OnMouseMove, [in, defaultvalue(0)] VARIANT userdata);
      // OnMouseMove(x, y)
      HRESULT SetOnKey([in, defaultvalue(0)] IDispatch *OnKey, [in, defaultvalue(0)] VARIANT userdata);
      // OnKey(key)
//      HRESULT SetOnMouseButton([in, defaultvalue(0)] IDispatch *pDisp, [in, defaultvalue(0)] VARIANT userdata);
      // OnMouseButton(x,y,button)
   }

   [uuid(AA9E1802-71D0-4E53-8E6E-2FD4A1326B97), oleautomation, dual, nonextensible]
   interface ArrayUInt : IDispatch
   {
      [propget, id(DISPID_VALUE)] HRESULT Item([in] VARIANT index, [out, retval] unsigned int *retval);
      [propget] HRESULT Count([out, retval] long *);
   }

   [ uuid(36A385C6-A258-4210-A61C-EB3890501903), oleautomation, dual, nonextensible ]
   interface TextWindowLine : IDispatch
   {
      [propget] HRESULT Length([out, retval] long *);
      [propget] HRESULT String([out, retval] BSTR *); 
      [propget] HRESULT HTMLString([out, retval] BSTR *);

      HRESULT Insert([in] unsigned int position, [in] TextWindowLine *line);
      HRESULT Delete([in] unsigned int start, [in] unsigned int end);

      HRESULT Color([in] unsigned int start, [in] unsigned int end, [in, defaultvalue(0)] long color);
      HRESULT BgColor([in] unsigned int start, [in] unsigned int end, [in, defaultvalue(0)] long color);

      HRESULT Bold([in] unsigned int start, [in] unsigned int end, [in, defaultvalue(1)] VARIANT_BOOL set);
      HRESULT Italic([in] unsigned int start, [in] unsigned int end, [in, defaultvalue(1)] VARIANT_BOOL set);
      HRESULT Underline([in] unsigned int start, [in] unsigned int end, [in, defaultvalue(1)] VARIANT_BOOL set);
      HRESULT Strikeout([in] unsigned int start, [in] unsigned int end, [in, defaultvalue(1)] VARIANT_BOOL set);
      HRESULT Flash([in] unsigned int start, [in] unsigned int end, [in, defaultvalue(1)] VARIANT_BOOL set);
      [helpstring("mode: 0 = normal, 1 = inverse")]
      HRESULT FlashMode([in] unsigned int start, [in] unsigned int end, [in, defaultvalue(0)] int mode);
      HRESULT Blink([in] unsigned int start, [in] unsigned int end, [in] unsigned int iBits, [in] unsigned int mask);
   }

    [ uuid(36A385C4-A258-4210-A61C-EB3890501903), dual, nonextensible ]
   interface Window_Text : IDispatch
   {
      [propget] HRESULT Properties([out, retval] Window_Properties **retval);
      [propget] HRESULT Paused([out, retval] VARIANT_BOOL *);

      HRESULT Create([in] BSTR text, [out, retval] TextWindowLine** retval);
      HRESULT CreateHTML([in] BSTR html, [out, retval] TextWindowLine** retval);
      HRESULT Add([in] TextWindowLine *line);
      HRESULT Write([in] BSTR text);
      HRESULT WriteHTML([in] BSTR html);

      HRESULT SetOnPause([in, defaultvalue(0)] IDispatch *pDisp);

//		[propget] HRESULT UserData([out, retval] VARIANT *pVar);
//		[propput] void UserData([in] VARIANT var);
   }

   [ uuid(9D4D0B72-ABAD-40C7-91E6-29B07F6DC721), oleautomation, dual, nonextensible ]
   interface Window_SpawnTabs : IDispatch
   {
      HRESULT SetOnTabActivate([in, defaultvalue(0)] IDispatch *OnTabActivate, [in, defaultvalue(0)] VARIANT userdata);
      // OnTabActivate(BSTR tab_name, var);
   }

   [ uuid(E50E3B98-5AE1-4fe7-814A-4B1B1A188EF2), oleautomation, dual, nonextensible ]
   interface Window_Input : IDispatch
   {
      HRESULT SetSel([in] int start, [in] int end);
      HRESULT GetSelStart([out, retval] int *retval);
      HRESULT GetSelEnd([out, retval] int *retval);

      [propget] HRESULT Length([out, retval] int *retval);

      [propget] HRESULT Prefix([out, retval] BSTR *retval);
      [propput] HRESULT Prefix([in] BSTR text);
      [propget] HRESULT Title([out, retval] BSTR *retval);
      [propput] HRESULT Title([in] BSTR text);

      HRESULT Set([in] BSTR bstr);
      HRESULT Get([out, retval] BSTR *retval);
   }

   [ uuid(479a8e11-1a05-464d-afec-6c32a7a3a3b5), oleautomation, dual, nonextensible ]
   interface Log : IDispatch
   {
      HRESULT Write([in] BSTR text);
      HRESULT WriteLine([in] TextWindowLine *line);

      [propget] HRESULT FileName([out, retval] BSTR *);
   }

   [ uuid(36A385C5-A258-4210-A61C-EB3890501903), oleautomation, dual, nonextensible ]
   interface Connection : IDispatch
   {
      HRESULT Send([in] BSTR text); // Text about to be sent
      [helpstring("Set the OnSend callback which is called when text is about to be sent over the network\n"
         "\n"
         "Callback function signature:\n"
         "  void OnSend(string text, var userdata)")]
      HRESULT SetOnSend([in, defaultvalue(0)] IDispatch *OnSend, [in, defaultvalue(0)] VARIANT userdata);
      [helpstring("Translates 'text' to the server's text encoding and sends it over the network")]
      HRESULT Transmit([in] BSTR text);

      [helpstring("Receive data as though the given string was received from the connection (in the server's text encoding). Processes telnet codes and then divides the resulting text into single lines that it will pass to Display()")]
      HRESULT Receive([in] BSTR text);
      [helpstring("Set the OnReceive callback which is called when text is received from the network (or by Receive being called)\n"
         "\n"
         "Callback function signature:\n"
         "  void OnReceive(string text, var userdata)")]
      HRESULT SetOnReceive([in, defaultvalue(0)] IDispatch *OnReceive, [in, defaultvalue(0)] VARIANT userdata);

      [helpstring("Parse a line of text for display (text is still in server's text encoding). Handles HTML/triggers/puppets/etc")]
      HRESULT Display([in] BSTR text);
      [helpstring("Set the OnDisplay callback which is called when a line of text is about to be displayed\n"
         "\n"
         "Callback function signature:\n"
         "  void OnDisplay(ITextWindowLine line, var userdata)")]
      HRESULT SetOnDisplay([in, defaultvalue(0)] IDispatch *OnDisplay, [in, defaultvalue(0)] VARIANT userdata);

      [helpstring("Set a callback for when an OOB GMCP message is received. The 'text' is the raw message, not split into tag/json\n"
         "\n"
         "Callback function signature:\n"
         "  void OnGMCP(string text, var userdata)")]
      HRESULT SetOnGMCP([in, defaultvalue(0)] IDispatch *OnGMCP, [in, defaultvalue(0)] VARIANT userdata);

      [helpstring("Set a callback for when a connection is made\n"
         "\n"
         "Callback function signature:\n"
         "  void OnConnect(var userdata)")]
      HRESULT SetOnConnect([in, defaultvalue(0)] IDispatch *OnConnect, [in, defaultvalue(0)] VARIANT userdata);
      [helpstring("Set a callback for when a disconnection happens\n"
         "\n"
         "Callback function signature:\n"
         "  void OnDisconnect(var userdata)")]
      HRESULT SetOnDisconnect([in, defaultvalue(0)] IDispatch *OnDisconnect, [in, defaultvalue(0)] VARIANT userdata);

      HRESULT IsConnected([out, retval] VARIANT_BOOL *);
      [helpstring("Tries to reconnect to the last server, returns true if successful. Failure is likely due to no last server or if we're already connected.")]
      HRESULT Reconnect([out, retval] VARIANT_BOOL *); // Returns TRUE if reconnect possible

      HRESULT IsLogging([out, retval] VARIANT_BOOL *);
      [propget] HRESULT Log([out, retval] Log **);

      [propget, helpstring("Currnet world (or null if there is no current world)")] HRESULT World([out, retval] World **);
      [propget, helpstring("Current character (or null if there is no current character)")] HRESULT Character([out, retval] Character **);
      [propget, helpstring("Current puppet (or null if there is no current puppet")] HRESULT Puppet([out, retval] Puppet **);

      [propget] HRESULT Window_Main([out, retval] Window_Main **retval);
   }

   typedef enum tagSide
   {
      Side_Left,
      Side_Top,
      Side_Right,
      Side_Bottom
   } Side;

   [ uuid(39ac8829-0e73-40d7-bec7-193c72e2a7cc), oleautomation, dual, nonextensible ]
   interface Docking : IDispatch
   {
      HRESULT Dock(Side side); // Docks the window to a particular side
   };

   [ uuid(36A385C1-A258-4210-A61C-EB3890501903), oleautomation, dual, nonextensible,
     helpstring("This is the main window (the tabs on the BeipMU taskbar are each one of these)")
   ]
   interface Window_Main : IDispatch
   {
      [propget] HRESULT Output([out, retval] Window_Text **retval);
      [propget] HRESULT History([out, retval] Window_Text** retval);
      [propget] HRESULT Input([out, retval] Window_Input** retval); // Gets the default input window
      [propget] HRESULT Connection([out, retval] Connection** retval);

      [propget] HRESULT UserData([out, retval] VARIANT *pVar);
      [propput] void UserData([in] VARIANT var);

      HRESULT GetInput([in] BSTR title, [out, retval] Window_Input **retval); // Gets secondary input windows by name
      HRESULT GetSpawnTabs([in] BSTR title, [out, retval] Window_SpawnTabs **retval); // Get spawn tabs window by name

      HRESULT Close();

      HRESULT SetOnCommand([in, defaultvalue(0)] IDispatch *OnCommand, [in, defaultvalue(0)] VARIANT userdata);
      HRESULT SetOnActivate([in, defaultvalue(0)] IDispatch *OnActivate, [in, defaultvalue(0)] VARIANT userdata);
      // OnActivate(ISocket sock, BSTR bstrData);
      HRESULT SetOnClose([in, defaultvalue(0)] IDispatch *OnClose, [in, defaultvalue(0)] VARIANT userdata);

      HRESULT Run([in] BSTR command);
      HRESULT RunFile([in] BSTR filename);

      HRESULT CreateDialogConnect(); // Fails if window is already connected

      [propget] HRESULT TitlePrefix([out, retval] BSTR *title);
      [propput] HRESULT TitlePrefix([in] BSTR title); // Sets the title prefix (what appears before BeipMU's automatic title)
      [propget] HRESULT Title([out, retval] BSTR *title); // Reads the current full title

      [helpstring("Show activity on this tab")] HRESULT Activity();
      [helpstring("Add important activity on this tab")] HRESULT AddImportantActivity();

      HRESULT GetVariable([in] BSTR name, [out, retval] BSTR *value);
      HRESULT SetVariable([in] BSTR name, [in] BSTR value);
      HRESULT DeleteVariable([in] BSTR name);
   }

   [ uuid(E9440711-EB4F-4250-AE95-5DB339E27C98), oleautomation, dual, nonextensible ]
   interface Windows : IDispatch
   {
      [propget, id(DISPID_VALUE)] HRESULT Item([in] VARIANT var, [out, retval] Window_Main** retval);
      [propget] HRESULT Count([out, retval] long *);
   }

   [ uuid(9B7F5272-55B2-43ef-9E46-545F8D866AD8), oleautomation, dual, nonextensible ]
   interface Window_FixedText : IDispatch
   {
      [propget] HRESULT Events([out, retval] Window_Events **retval);
      [propget] HRESULT Properties([out, retval] Window_Properties **retval);

      [propget] HRESULT CursorX([out, retval] int *pX);
      [propput] HRESULT CursorX([in] int X);
      [propget] HRESULT CursorY([out, retval] int *pY);
      [propput] HRESULT CursorY([in] int Y);

      HRESULT Clear();
      HRESULT Write([in] BSTR);
   }

   [ uuid(2531C240-64EA-4293-B08A-A9C1F9271627), oleautomation, dual, nonextensible ]
   interface Timer : IDispatch
   {
      [propget] HRESULT UserData([out, retval] VARIANT *pVar);
      [propput] void UserData([in] VARIANT var);

      void Kill();
      [propget] HRESULT Active([out, retval] VARIANT_BOOL *retval);
   }

   [ uuid(71569D4A-704F-4fb3-8F18-CE0E0EE634F3), oleautomation, dual, nonextensible ]
   interface Window_Graphics : IDispatch
   {
      [propget] HRESULT Events([out, retval] Window_Events **retval);
      [propget] HRESULT Properties([out, retval] Window_Properties **retval);

      [propget] HRESULT Width([out, retval] int *);
      [propget] HRESULT Height([out, retval] int *);

      HRESULT Clear([in, defaultvalue(0)] long lColor);

      HRESULT SetPixel([in] int x, [in] int y, [in] long lColor);
      HRESULT GetPixel([in] int x, [in] int y, [out, retval] long *);

      HRESULT SetPen([in] long lColor, [in, defaultvalue(0)] int width);
      HRESULT MoveTo([in] int x, [in] int y);
      HRESULT LineTo([in] int x, [in] int y);

      HRESULT Text([in] int x, [in] int y, [in] BSTR text);
   }

   [ uuid(06815526-b219-411c-bf00-afe01930db8b), oleautomation, dual, nonextensible ]
   interface Socket : IDispatch
   {
      HRESULT Connect([in] BSTR host, [in, defaultvalue(1234)] unsigned int iPort);
      HRESULT Close();
      HRESULT IsConnected([out, retval] VARIANT_BOOL *);

      HRESULT Send([in] VARIANT send);

      HRESULT SetOnReceive([in, defaultvalue(0)] IDispatch *pDisp);
      // OnReceive(ISocket sock, BSTR buffer);
      HRESULT SetOnConnect([in, defaultvalue(0)] IDispatch *pDisp);
      // OnConnectEvent(ISocket sock);
      HRESULT SetOnDisconnect([in, defaultvalue(0)] IDispatch *pDisp);
      // OnDisconnectEvent(ISocket sock);

      HRESULT SetFlag([in] int iFlag, [in] VARIANT_BOOL fValue);
      // Flags:
      // 1 = Only send entire lines to OnReceive (wait for carriage returns/line feeds)

      [propget] HRESULT UserData([out, retval] VARIANT *pVar);
      [propput] void UserData([in] VARIANT var);
   }

   [ uuid(1942893B-C4F0-410D-8348-D69DE3174CFB), dual, nonextensible ]
   interface WebView : IDispatch
   {
      HRESULT CloseWindow();

      HRESULT IsConnected([out, retval] VARIANT_BOOL *retval);
      [helpstring("Callback function signature: void OnConnect()")]
      HRESULT SetOnConnect([in] IDispatch *OnConnect);
      [helpstring("Callback function signature: void OnDisconnect()")]
         HRESULT SetOnDisconnect([in] IDispatch *OnDisconnect);

      HRESULT Send([in] BSTR bstr, [in, defaultvalue(0)] VARIANT_BOOL process_aliases); // Send the given string as text over the socket
      [helpstring("Called right before text is sent to the server\n"
         "Callback function signature: void OnSend(string text_sent)")]
      HRESULT SetOnSend([in] IDispatch *p_callback);

      HRESULT Receive([in] BSTR bstr); // Act as though the given string was received from the connection
      [helpstring("Called when text is received (before being displayed)\n"
         "Callback function signature: void OnReceive(string text_received)")]
         HRESULT SetOnReceive([in] IDispatch *p_callback);

      HRESULT Display([in] BSTR bstr);
      [helpstring("Register a callback to call when text is about to be displayed. The regex filters which lines reach the callback. Gag will cause the line to not be displayed in the UI.\n"
         "Callback function signature: void OnDisplay(int id, ITextWindowLine line)")]
      HRESULT SetOnDisplay([in] int id, [in] IDispatch *p_callback, [in] BSTR regex, [in, defaultvalue(0)] VARIANT_BOOL gag);
      HRESULT ClearOnDisplay([in] int id);

      [helpcontext(1)]
      HRESULT SetOnDisplayCapture([in] int id, [in] IDispatch *OnCapture, [in] IDispatch *OnCaptureChanged, [in] BSTR regex_begin, [in] BSTR regex_end);
      HRESULT ClearOnDisplayCapture([in] int id, [out, retval] VARIANT_BOOL *success);

      HRESULT SendGMCP([in] BSTR package, [in] BSTR json);
      [helpstring("Adds the callback and the package_prefix to the list of GMCP handlers. When a GMCP message is received, if a prefix matches it will call the given callback.\n"
         "Callback function signature: void OnGMCP(string package, string json)")]
      HRESULT SetOnGMCP([in] BSTR package_prefix, [in] IDispatch *OnGMCP);
      [helpstring("Removes the callback with package_prefix from the list of GMCP handlers.")]
      HRESULT ClearOnGMCP([in] BSTR package_prefix);

      HRESULT ProcessAliases([in] BSTR text, [out, retval] BSTR *result);
      HRESULT AddToInputHistory([in] BSTR text);

      [helpstring("Gets a string property from the webview. Here's the list of available properties:\n"
         "WorldName - Name of current world\n"
         "CharacterName - Name of current character\n"
         "PuppetName - Name of current puppet\n"
         "ID - ID the webview was created with")]
      HRESULT GetPropertyString([in] BSTR property, [out, retval] BSTR *result);
   }

   [ uuid(5b53fd39-46a8-4519-86a4-0442d98d79aa), oleautomation, dual, nonextensible ]
   interface SocketServer : IDispatch
   {
      HRESULT Shutdown();
      // OnConnection(ISocket sock);
   }

   [ uuid(334038f2-b7e7-4a0d-af86-eca67b6f82ff), oleautomation, dual, nonextensible ]
   interface ReverseDNS : IDispatch
   {
      // The object created during a RevereDNS lookup (hidden currently)
   };

   [ uuid(daae34c6-1e89-410e-a095-eb1f8c2777a7), oleautomation, dual, nonextensible ]
   interface ForwardDNS : IDispatch
   {
      // The object created during a ForwardDNS lookup (hidden currently)
   };

   [ uuid(36A385C8-A258-4210-A61C-EB3890501903), oleautomation, dual, nonextensible ]
   interface App : IDispatch
   {
      [propget] HRESULT BuildNumber([out, retval] long *);
      [propget] HRESULT BuildDate([out, retval] DATE *);
      [propget] HRESULT Version([out, retval] long *);

      [propget] HRESULT Worlds([out, retval] Worlds **retval);
      [propget] HRESULT Windows([out, retval] Windows **retval);
      [propget] HRESULT Triggers([out, retval] Triggers **retval);
      [propget] HRESULT Aliases([out, retval] Aliases **retval);

      [propget] HRESULT ConfigPath([out, retval] BSTR *retval);

      HRESULT ActiveXObject([in] BSTR name, [out, retval] IDispatch **retval);

      HRESULT NewTrigger([out, retval] Trigger **retval);

      HRESULT NewWindow_FixedText([in, defaultvalue(80)] int width, [in, defaultvalue(25)] int height, [out, retval] Window_FixedText** retval);
      HRESULT NewWindow_Graphics([in] int width, [in] int height, [out, retval] Window_Graphics** retval);
      HRESULT NewWindow_Text([in, defaultvalue(320)] int width, [in, defaultvalue(240)] int height, [out, retval] Window_Text** retval);

      HRESULT NewWindow([out, retval] Window_Main** retval);
      HRESULT SetOnNewWindow([in, defaultvalue(0)] IDispatch *OnNewWindow, [in, defaultvalue(0)] VARIANT userdata);

      [helpcontext(2)]
      HRESULT CreateInterval([in] int time_in_ms, [in] IDispatch *OnTimer, [in, defaultvalue(0)] VARIANT userdata, [out, retval] Timer **retval);

      [helpcontext(3)]
      HRESULT CreateTimeout([in] int time_in_ms, [in] IDispatch *OnTimer, [in, defaultvalue(0)] VARIANT userdata, [out, retval] Timer **retval);

      HRESULT New_Socket([out, retval] Socket **retval);
      HRESULT New_SocketServer([in] unsigned int port, 
                               [in] IDispatch *OnConnection, [in, defaultvalue(0)] VARIANT userdata,
                               [out, retval] SocketServer **retval);

      [helpstring(
         "Callback function signature: <font color='lime'>OnLookup</font>(string hostname, variant userdata)\n"
         "\n"
         "Example Usage:\n"
         "function Lookup(hostname) { window.output.write(hostname); }\n"
         "app.ReverseDNSLookup(\"127.0.0.1\", Lookup);")]
      HRESULT ReverseDNSLookup([in] BSTR ip_address, [in] IDispatch *OnLookup, [in, defaultvalue(0)] VARIANT userdata);

      [helpstring(
         "Callback function signature: OnLookup(string hostip, variant userdata)\n"
         "\n"
         "Example usage:\n"
         "function Lookup(hostip) { window.output.write(hostip); }\n"
         "app.ForwardDNSLookup(\"www.msn.com\", Lookup);")]
      HRESULT ForwardDNSLookup([in] BSTR hostname, [in] IDispatch *OnLookup, [in, defaultvalue(0)] VARIANT userdata);

      HRESULT IsAddress([in] BSTR ip_address, [out, retval] VARIANT_BOOL *pResult);

      HRESULT PlaySound([in] BSTR filename, [in, defaultvalue(1.0)] float volume);
      HRESULT StopSounds();

      HRESULT OutputDebugHTML([in] BSTR html);
      HRESULT OutputDebugText([in] BSTR text);
   }

   [ uuid(36A385C7-A258-4210-A61C-EB3890501903), oleautomation, dual, nonextensible ]
   interface Beip : IDispatch
   {
      [propget] HRESULT Window([out, retval] Window_Main** retval);
      [propget] HRESULT App([out, retval] App** retval);
   }
}
