#define ID_EDIT_PASTE                   0xE125
#define ID_EDIT_COPY                    0xE122
#define ID_EDIT_FIND                    0xE124

#define ID_FILE_QUIT                    1000
#define ID_HELP_ABOUT                   1001
#define ID_HELP_CONTENTS                1002
#define ID_CONNECTION_CONNECT           1006
#define ID_CONNECTION_DISCONNECT        1007
#define ID_LOGGING_START                1008
#define ID_LOGGING_STOP                 1009
#define ID_MUTE                         1010
#define ID_FILE_NEWWINDOW               1011
#define ID_LOGGING                      1012
#define ID_FILE_NEWTAB                  1013
#define ID_FILE_CLOSEWINDOW             1016
#define ID_OPTIONS_PREFERENCES          1017
#define ID_EDIT_SMARTPASTE              1018
#define ID_OPTIONS_MACROS               1023
#define ID_EDIT_SELECTALL               1024
#define ID_EDIT_FINDINPUTHISTORY        1025
#define ID_OPTIONS_INPUT_HISTORY        1026
#define ID_OPTIONS_ALIASES              1034
#define ID_OPTIONS_TRIGGERS             1035
#define ID_LOGGING_FROMBEGINNING        1036
#define ID_STATIC_ABOUTINFO             1040
#define ID_CONNECTION_RECONNECT         1041
#define ID_HELP_CHANGES                 1043
#define ID_HELP_DEBUG_NETWORK           1051
#define ID_HELP_DEBUG_TRIGGERS          1052
#define ID_FILE_NEWINPUT                1053
#define ID_EDIT_COPYDOCKING             1059
#define ID_EDIT_PASTEDOCKING            1060
#define ID_FILE_CLOSETAB                1061
#define ID_OPTIONS_IMAGEWINDOW          1063
#define ID_TABCOLOR                     1064
#define ID_TABCOLORDEFAULT              1065
#define ID_FILE_NEWEDIT                 1067
#define ID_OPTIONS_CHARNOTESWINDOW      1068
#define ID_LOGGING_FROMWINDOW           1069
#define ID_OPTIONS_MAPWINDOW            1070
#define ID_OPTIONS_SHOWHIDDENCAPTIONS   1072
