//
// All Localized Strings
//
// GERMAN
//

// General Usage
#define STR_Sample "Beispiel"
#define STR_Key "Taste"
#define STR_PressKeyHere "Taste drücken:"
#define STR_Modifiers "Umschalttasten"
#define STR_Control "Steuerung"
#define STR_Alt "Alt"
#define STR_Shift "Shift"
#define STR_Default "Standardwerte"
#define STR_Done "Fertig"
#define STR_Font "Schrift"
#define STR_Time "Zeit"
#define STR_Date "Datum"
#define STR_24Hour "24h"
#define STR_Browse___ "Durchsuchen..."

// Misc
#define STR_Lines "Zeilen"
#define STR_Empty "(leer)"

// Connect Dialog
#define STR_DirectConnect "Direktverbinden"
#define STR_Direct "Direkt"
#define STR_Host "Adresse"
#define STR_Port "Port"

#define STR_Title_Worlds "Welten"
#define STR_NoName "(namenlos)"
#define STR_PuppetNeedsCharacter "Verbindung zum Zombie nicht möglich, solange der zugehörige Charakter nicht eingeloggt ist."
#define STR_Note "Achtung:"

#define STR_New "Neu"
#define STR_Connect "Verbinden"
#define STR_Rename "Umbenennen"
#define STR_Delete "Löschen"
#define STR_OK "Ok"
#define STR_Apply "Apply (English)"
#define STR_Cancel "Abbruch"
#define STR_ShortcutCantBeBlank "Abkürzungen dürfen nicht leer gelassen werden."
#define STR_CharacterShortcutsMustBeUnique "Charaktere müssen einzigartige Abkürzungen haben!"
#define STR_ServerShortcutsMustBeUnique "Server müssen einzigartige Abkürzungen haben!"
#define STR_Menu_Server "&Server"
#define STR_Menu_Character "&Charakter"
#define STR_Menu_Puppet "&Zombie"
#define STR_AreYouSure "Sine sie sicher?"
#define STR_CharacterNameAlreadyExists "Ein Charakter mit diesem Namen existiert bereits für diesen Server"

// Character Dialog
#define STR_Unknown "unbekannt"
#define STR_CurrentlyInUse "gerade verbunden"
#define STR_SincePrefix "vor "
#define STR_SinceSuffix ""
#define STR_Character "Charakter"
#define STR_Name "Name"
#define STR_ConnectString "Verbindungs-\rbefehl"
#define STR_Info "Info"
#define STR_LogFile "Logdatei..."
#define STR_AppendDateToLogFileName "Datum an Logdateinamen anhängen"
#define STR_LastUsed "letzte Benutzung:"
#define STR_DateCreated "Erschaffungsdatum:"
#define STR_AutomaticLogFile "automatische Logdatei"
#define STR_LogFileFilter "Textdateien (*.txt)\0*.txt\0Alle Dateien (*.*)\0*.*\0\0"

// Puppet Dialog
#define STR_Puppet "Zombie"
#define STR_ReceivePrefix "Empfangspräfix"
#define STR_SendPrefix "Sendepräfix"
#define STR_AutoConnect "automatisch verbinden"
#define STR_ConnectWithPlayer "verbinden wenn Charakter verbunden"

// Server Dialog
#define STR_ExtensionMissing "Servertyp ist nicht installiert und kann nicht verwendet werden"
#define STR_Server "Server"
#define STR_HandleHTMLTags "HTML-Tags verarbeiten"
#define STR_MUDPromptHandling "MUD Prompt Arbeitsweise"
#define STR_Type "Typ"

// Aliases
#define STR_ProcessAliases "Aliase verarbeiten"
#define STR_EchoProcessedAliases "verarbeiteten Alias ausgeben"
#define STR_Alias_MatchText "Aliastext:"
#define STR_MatchCase "Groß/Kleinschreibung"
#define STR_WholeWord "ganzes Wort"
#define STR_LineStartsWith "Zeile beginnt mit"
#define STR_LineEndsWith "Zeile endet mit"
#define STR_AliasFor "Alias für:"
#define STR_Global "Global"
#define STR_Aliases "Aliase"

// Ansi Colors
#define STR_AnsiColors "ANSI-Farben"
#define STR_TextColors "Textfarben"

#define STR_Change "Ändern"
#define STR_AnsiDefaults "ANSI-Standards"
#define STR_BrightDefaults "helle Standards"
#define STR_Appearance "Schriftbild"
#define STR_PreventInvisible "unsichtbaren Text vermeiden"
#define STR_ResetOnNewLine "bei Zeilenumbruch Werte zurücksetzen"
#define STR_UseFontBold "fette Schrift statt fetter Farben"
#define STR_ms "ms"
#define STR_Beep "Beep"
#define STR_EnableBeep "Beep aktivieren"
#define STR_UseSystemBeep "System-Beep verwenden"
#define STR_Custom "eigener"
#define STR_Play "Abspielen"
#define STR_Change___ "Durchsuchen..."
#define STR_ParseAnsi "ANSI-Farbcodes verarbeiten"
#define STR_SoundFile "Audiodatei"
#define STR_SoundFileFilter "Audiodateien (*.wav)\0*.wav\0Alle Dateien (*.*)\0*.*\0\0"
#define STR_CantPlaySound "Sound kann nicht abgespielt werden."
#define STR_Error "Fehler:"

// Find Dialog
#define STR_SearchTextNotFound "Suchtext nicht gefunden"

// Font Dialog
#define STR_Font___ "Schriftart..."
#define STR_Foreground___ "Vordergrund..."
#define STR_Background___ "Hintergrund..."
#define STR_AaBbCc "AaBbCcXxYyZz"

// Key Dialog
#define STR_Title_Key "Taste"
#define STR_PressKeyCombination "Drücken sie jetzt\ndie Tastekombination.\n\nMausklick zum Abbrechen"
#define STR_PressKey___ "Taste drücken..."

// Keyboard Macros
#define STR_ProcessKeyboardMacros "Tatstaturmakros Aktivieren"
#define STR_MacroText "Makrotext"
#define STR_TypeIntoInputWindow "ins Eingabefenster schreiben"
#define STR_MacroLimitations "Achtung: Makros mit den Buchstaben 'A'-'Z' werden\nnur zusammen mit Alt oder Steuerung funktionieren."
#define STR_Title_KeyboardMacros "Tastaturmakros"

// Keyboard Shortcuts
#define STR_Title_KeyboardShortcuts "Tastenkürzel"
#define STR_Clear "Löschen"
#define STR_ResetAll "Alles zurücksetzen"
#define STR_Action "Aktion"

// Logging
#define STR_Title_Logging "Log-Optionen"
#define STR_WhatGetsLogged "Was wird aufgezeichnet?"
#define STR_Sent "gesendet"
#define STR_Typed "getippt"
#define STR_FileDateFormat "Datumsformat für Logdatei"
#define STR_FormatString "Formatierung:"
#define STR_DateAndTimePerLine "Datum && Zeit pro Zeile"
#define STR_Advanced "Fortgeschritten"
#define STR_Wrapping "Umbrüche"
#define STR_WrapText "Text umbrechen"
#define STR_TextCharacters "Zeilenbreite:"
#define STR_HangingIndent "Überhang einrücken"
#define STR_WrapNearestWord "ganze Wörter umbrechen"
#define STR_FileDateFormatString "yyyy'-'MM'-'dd"

// Preferences
#define STR_Title_Preferences "Einstellungen"
#define STR_ActivityNotify "Benachrichtigung bei Aktivität"
#define STR_None "keine"
#define STR_Blink "blinken"
#define STR_Solid "konstant"
#define STR_Connections "Verbindungen"
#define STR_ConnectTimeout "Verbindungstimeout "
#define STR_ConnectRetry "Wiederholung bis zu "
#define STR_Seconds "Sekunden"
#define STR_RetryForever "endlos wiederholen"
#define STR_Times "Mal "
#define STR_StripTrailingSpaces "Leerzeichen am Zeilenende entfernen"
#define STR_Alerts "Warnungen"
#define STR_AskBeforeDisconnecting "Fragen, wenn ein Fenster geschlossen wird, das verbunden ist"
#define STR_AskBeforeClosing "Fragen, wenn ein Fenster geschlossen wird (verbunden oder nicht)"
#define STR_Windows "Fenster"
#define STR_ShowSplash "Begrüßungsbildschirm beim Starten anzeigen"
#define STR_NotificationIcon "Anzeige Benachrichtigung Symbol auf der Taskleiste"
#define STR_ScrollDelay "Scrollverzögerung (ms) "
#define STR_ActivateDisconnect "bei Verbindungsabbruch aktivieren"
#define STR_Networking "Vernetzung"
#define STR_TCP_KeepAlive "anschalten TCP Keepalives (TCP_KEEPALIVE)"
#define STR_TCP_NoDelay "Deaktivieren Nagle-Algorithmus (TCP_NODELAY)"
#define STR_Scripting "Scripting"
#define STR_Language "Sprache "
#define STR_StartupScript "Startskript "
#define STR_DebuggingMode "Debugmodus"
#define STR_BuildingList "(Liste wird erstellt...)"

// Smart Paste
#define STR_Title_SmartPaste "Einfügen aus..."
#define STR_FileToPaste "Datei zum Einfügen"
#define STR_PasteFileFilter "Textdateien (*.txt)\0*.txt\0JPG Bild (*.jpg)\0*.jpg\0GIF Bild (*.gif)\0*.gif\0Alle Dateien (*.*)\0*.*\0\0"
#define STR_FileNotFound "Datei nicht gefunden"
#define STR_FileLarger64K "Die Datei ist größer als 64Kb, die Operation könnte eine Weile dauern. Trotzdem einfügen?"
#define STR_CantReadFile "Datei konnte nicht geladen werden!"
#define STR_LinesPasted " Zeilen eingefügt."
#define STR_BytesSent " Bytes versandt."
#define STR_Source "Quelle"
#define STR_Clipboard "Zwischenablage"
#define STR_File "Datei"
#define STR_ClipboardPreview "Vorschau Zwischenablage"
#define STR_Prefix "Präfix"
#define STR_Suffix "Suffix"
#define STR_Paste "Einfügen"
#define STR_Bytes "Bytes:"

// Text Window
#define STR_Title_TextWindow "Textfenstereinstellungen"
#define STR_Title_InputWindow "Einstellungen für Eingabefenster"
#define STR_Size "Größe"
#define STR_Text "Text"
//#define STR_BackgroundImage "Hintergrundbild"
//#define STR_Style "Stil:"
//#define STR_Normal "normal"
//#define STR_Tiled "gekachelt"
//#define STR_Scaled "gestreckt"
#define STR_General "allgemein"
#define STR_WrappedLineIndent "einrücken nach autom. Zeilenumbruch"
#define STR_ParagraphSpacing "Paragraph Spacing (English) "
#define STR_HistoryLines "Zeilen im Verlauf  "
#define STR_FixedWidth "feste Breite"
#define STR_Characters "Zeichen"
#define STR_ScrollToBottomOnAdd "bei neuem Text ans untere Ende scrollen"
#define STR_DateTimeDisplay "Datums- && Zeitanzeige"
#define STR_DateTimeTooltip "Datum && Zeit als ToolTip"
#define STR_Margins "Ränder"
#define STR_Left "links"
#define STR_Top "oben"
#define STR_Right "rechts"
#define STR_Bottom "unten"
#define STR_Pixels "Pixel"
#define STR_ImageFile "Bilddatei"
#define STR_Options "Optionen"
#define STR_PendingLines "Anhängig Textzeile"

// Triggers
#define STR_Title_Appearance "Appearance (English)"
#define STR_ChangeForeground "Vordergrund ändern"
#define STR_ChangeBackground "Hintergrund ändern"
#define STR_WholeLine "ganze Zeile"
#define STR_Title_Style "Stil"
#define STR_Bold "fett"
#define STR_Italic "kursiv"
#define STR_Underline "unterstrichen"
#define STR_Strikeout "durchgestrichen"
#define STR_Flashing "blinkend"
#define STR_Title_Sound "Sound"
#define STR_PlaySound "Sound abspielen"
#define STR_Title_Gag "ignorieren"
#define STR_GagThisLine "diese Zeile ignorieren"
#define STR_GagLineInLog "diese Zeile nicht ins Logfile schreiben"
#define STR_GagMessage "Knebelmeldung (zum testen)"
#define STR_Title_Activate "Aktivieren"
#define STR_ActivateOnTrigger "Fenter aktivieren, wenn ausgelöst"

#define STR_Title_Script "Script"
#define STR_Title_Toast "Toast"
#define STR_ToastOnTrigger "Toast Message when trigger hits"
#define STR_Enabled "Enabled"
#define STR_FunctionToCall "Function To Call"

#define STR_FunctionExample "The function being called should look something like this:\rfunction Sample(/*IWindow_Main*/ window, /*ITextWindowLine*/ text)\r{\r  window.output.add(text);\r} (English)"
#define STR_Title_Extensions "Erweiterungen"
#define STR_Title_Send "senden"
#define STR_SendText "Text senden"
#define STR_TextToSend "Text zum senden:"
#define STR_Title_Filter "Filter"
#define STR_FilterText "Text Filtern"

#define STR_FilterHTML "Parse HTML Tags on replacement"

#define STR_TextFilteredWith "Text, mit dem ersetzt werden soll:"
#define STR_CharacterServerGlobal "Charakter, Server, Global"
#define STR_GlobalServerCharacter "Global, Server, Charakter"
#define STR_ProcessingOrder "Verarbeitungsreihenfolge:"
#define STR_ProcessTriggers "Auslöser in diesem Element verarbeiten"
#define STR_RegularExpression "regulärer Ausdruck"
#define STR_Disabled "Deaktiviert"
#define STR_StopProcessing "Verarbeitung abbrechen"
#define STR_OncePerLine "einmal pro Zeile"
#define STR_OnlyWhen "nur wenn:"
#define STR_Away "abwesend"
#define STR_Present "anwesend"
#define STR_Once "einmal"
#define STR_ChildTriggersDelete "Dieser Auslöser hat Unterauslöser, ihn zu löschen hieße, diese auch zu löschen. Sind sie sicher?"
#define STR_Warning "Warnung:"
#define STR_Title_Triggers "Auslöser"

#define STR_ForTheMasses " - Ein Client für die Massen!\nVersion "

// Connection
#define STR_CantReconnect "<font color='teal'>Neuverbindung nicht möglich, keine vorherige Verbindung"
#define STR_TryingToReconnect "<font color='teal'>CLIENT> Senden fehlgeschlagen, versuche Neuverbindung (sie können eine Verbindungstrennung erzwingen)"
#define STR_HTML_NotConnected "<font color='teal'>CLIENT> Nicht verbunden!"
#define STR_UsingLastIP "<font color='lime'>Adressauflösung fehlgeschlagen, benutze gespeicherte IP - "
#define STR_HostAddressFound "<font color='lime'>Serveradresse gefunden - "
#define STR_Connecting "<font color='lime'>, verbinde..."
#define STR_Retrying "<font color='aqua'>Neuer Versuch, Nummer "
#define STR_ConnectionTimedOut "<font color='teal'>Verbindungstimeout"
#define STR_ConnectingToPort " <font color='teal'>Port <font color='aqua'>"
#define STR_LookingUpHostName "<font color='teal'>Löse Hostnamen auf... "
#define STR_ConnectingTo "<font color='teal'>Verbinde zu <font color='aqua'>"
#define STR_PuppetCantConnect "<font color='red'>Zombieverbindung konnte nicht hergestellt werden, weil der zugehörige Charakter nicht verbunden ist!"
#define STR_CantConnectTo "<font color='teal'>Verbindung zu <font color='aqua'>"
#define STR_BecauseEmptyHostAddress "<font color='teal'> unmöglich weil die Hostadresse leer ist."
#define STR_ModuleNotInstalled "<font color='teal'>Clientmodul für diesen Servertyp nicht installiert:"
#define STR_ConnectingCharacter "Verbinde Charakter "
#define STR_Connected "<font color='blue'>*<font color='lime'>Verbunden<font color='blue'>*"
#define STR_Disconnected "<font color='maroon'>*<font color='red'>Verbindung getrennt<font color='maroon'>*"
#define STR_WillRetry "<font color='aqua'>Neuversuch wenn Verbindungstimeout abgelaufen."
#define STR_LineWasGagged "Zeile wurde ignoriert"
#define STR_LineGaggedInLog "Zeile wurde nicht in die Logdatei geschrieben"

// Logging
#define STR_CantCreateLogfile "<font color='red'>Logdatei konnte nicht angelegt werden "
#define STR_AppendingToExisting "<font color='green'>Füge an existierende Logdatei an: "
#define STR_LoggingStarted_ToLog "Aufzeichnung begonnen: "
#define STR_LoggingToFile "<font color='red'>Aufzeichnung in Logdatei "
#define STR_LoggingStarted " begonnen"
#define STR_NoLog "<font color='red'>Es wird momentan nichts aufgezeichnet."
#define STR_LoggingStopped_ToLog "Aufzeichnung beendet: "
#define STR_LoggingStopped "<font color='aqua'>Aufzeichnung beendet"
#define STR_LoggingWindowContents "<font color='red'>Momentaner Inhalt des Ausgabefensters wird abgespeichert..."

// Fixed Text
#define STR_Title_FixedText "dicktengleicher Text"

// Graphics
#define STR_Menu_Clear "Löschen"
#define STR_Menu_SaveAs "Speichern unter..."
#define STR_Menu_ScaleToFit "Strecken"
#define STR_SaveDataAs "Daten speichern unter..."
#define STR_GraphicsFilter "Alle Dateien (*.*)\0*.*\0\0"

// Main Window
#define STR_CouldLoadConfigFile "Achtung: Die Originalkonfiguration konnte nicht geladen werden. Ein Abspeichern würde die dort enthaltenen Daten vernichten. Trotzdem speichern?"
#define STR_CantDeleteBackupConfig "Die Sicherungsdatei konnte nicht gelöscht werden, wollen sie ohne Sicherungskopie abspeichern?"
#define STR_CantDeleteConfig "Existente Konfiguration konnte nicht entfernt werden."
#define STR_CannotMoveConfig "Existente Konfiguration konnte nicht in die Sicherheitskopie geschrieben werden."
#define STR_CHMNotFound "BeipMU.chm nicht im Anwendungsordner gefunden."
#define STR_AskReconnect "Erneut mit letztem Server verbinden?"
#define STR_NotConnected "nicht verbunden"
#define STR_Logging "Aufzeichnen"
#define STR_NoScriptingEngine "Skriptengine nicht vorhanden oder nicht initialisierbar."
#define STR_ErrorInitingScript "Fehler beim initialisieren der Skriptengine."
#define STR_CantLoadStartupScript "<font color='red'>Startskript konnte nicht geladen werden."
#define STR_StillConnected "Verbindung steht, sicher, dass sie beenden wollen?"
#define STR_CloseWindow "Fenster schließen"
//#define STR_AlreadyConnected "<font color='teal'>CLIENT> Bereits verbunden!"
#define STR_LogToFile "in Datei aufzeichnen"
#define STR_Online "Online"
#define STR_Idle "Idle"
#define STR_Windows "Fenster"
#define STR_HowToNotDock "Hold CTRL To Prevent Docking"

// About Dialog
#define STR_Title_About "Info"
#define STR_WebLink "http://www.beipmu.com"
#define STR_EmailLink "beipdev@yahoo.com"
#define STR_TheTeam "Das Team:"
#define STR_Team \
      "Bennet - Programmierung\n" \
      "Bryan 'Sennard' Travis - Design, Tests && Verpflegung\n" \
      "Jamie 'Squirrelly' Wilmoth - Skriptdesign and Skripte\n" \
      "Nordica Raapana - Folter, Illustration, Schmerz && Leid\n" \
      "Kris 'Krishva' Jacque - Webdesign, Illustration && Compy\n" \
      "Moritz 'Thygrrr' Voß - deutsche Fassung"
#define STR_Rights "BeipMU © CompySoft Productions\nAlle vorbehaltbaren Rechte sind es auch!"

// Find Dialog
#define STR_Title_Find "Suchen"
#define STR_Find_RegularExpression "&regulärer Ausdruck"
#define STR_Find_Down "A&bwärts"
#define STR_Find_Up "&Aufwärts"
#define STR_Find_MatchCase "&Groß/Kleinschreibung"
#define STR_Find_WholeWord "ganze &Wörter"
#define STR_Find_FindNext "&Weitersuchen"
#define STR_Find_MatchText "Suchhbegriff:"
#define STR_Find_Direction "Richtung"
